'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { BookOpenCheck, Check, ChevronRight, Clock3, Download, FileText, Link2, Pencil, Plus, QrCode, Sparkles, UploadCloud, Users, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

type Question = { type:'single'|'multiple'|'judge'|'fill'|'short'|'case'; stem:string; options?:string[]; answer?:number|number[]|string[]|boolean; score:number };

const sample: Question[] = [
  { type:'single', stem:'在 HTTP 状态码中，表示“未授权”的是？', options:['200','301','401','500'], answer:2, score:5 },
  { type:'multiple', stem:'以下哪些属于关系型数据库？', options:['MySQL','PostgreSQL','MongoDB','Redis'], answer:[0,1], score:10 },
  { type:'fill', stem:'Git 中用于创建新分支的命令是 ____。', answer:['git branch'], score:5 },
  { type:'case', stem:'某业务系统在促销期间响应缓慢，请分析可能的瓶颈，并提出排查与优化方案。', score:20 },
];

function parseQuestionsStable(text:string):Question[]{const lines=text.replace(/\r/g,'').split('\n').map(x=>x.trim()).filter(Boolean);const out:Question[]=[];let section:Question['type']='single',group:string[]=[];const flush=(ans:string)=>{if(!group.length)return;let stem=group[0].replace(/^\d+[.、．)]\s*/,'');let rest=group.slice(1);const marked=rest.filter(x=>/^[A-FＡ-Ｆ][.、．)、：:\s]/i.test(x));let options=marked.length?rest.map(x=>x.replace(/^[A-FＡ-Ｆ][.、．)、：:\s]*/i,'')).filter(Boolean):rest;const letters=(ans.match(/[A-F]/gi)||[]).map(x=>x.toUpperCase().charCodeAt(0)-65);let type:Question['type']=section;if(type==='single'&&letters.length>1)type='multiple';if(type==='judge')return out.push({type,stem,options:['正确','错误'],answer:/^(正确|对|是|TRUE)/i.test(ans),score:2});if(type==='fill')return out.push({type,stem,answer:[ans],score:5});if(type==='short'||type==='case')return out.push({type,stem,answer:type==='short'?[ans]:undefined,score:type==='case'?20:10});if(options.length>=2)out.push({type,stem,options,answer:type==='multiple'?letters:(letters[0]??0),score:type==='multiple'?4:3});group=[]};for(const line of lines){if(/^单选题\s*$/.test(line)){flush('');section='single';continue}if(/^多选题\s*$/.test(line)){flush('');section='multiple';continue}if(/^判断题\s*$/.test(line)){flush('');section='judge';continue}if(/^填空题\s*$/.test(line)){flush('');section='fill';continue}if(/^简答题\s*$/.test(line)){flush('');section='short';continue}if(/^案例分析/.test(line)){flush('');section='case';continue}if(/^(答案|正确答案|参考答案)\s*[:：]?/i.test(line)){flush(line.replace(/^(答案|正确答案|参考答案)\s*[:：]?/i,'').trim());continue}group.push(line)}flush('');return out}

function parseQuestionsCompat(text:string):Question[]{const lines=text.replace(/\r/g,'').split('\n').map(x=>x.trim()).filter(Boolean);const out:Question[]=[];let section:Question['type']='single',group:string[]=[],insideSection=false;const heading=/^(?:[一二三四五六七八九十\d]+\s*[、.．)]\s*)?(单选题|多选题|判断题|填空题|简答题|案例分析|案例题)/;const flush=(ans:string)=>{if(!group.length)return;const stem=group[0].replace(/^\d+[.、．)]\s*/,'');const rest=group.slice(1).flatMap(x=>x.split(/(?=[A-FＡ-Ｆ][.、．)、：:\s])/).map(y=>y.trim()).filter(Boolean));const marked=rest.filter(x=>/^[A-FＡ-Ｆ][.、．)、：:\s]/i.test(x));const options=marked.length?rest.map(x=>x.replace(/^[A-FＡ-Ｆ][.、．)、：:\s]*/i,'')).filter(Boolean):rest;const letters=(ans.match(/[A-F]/gi)||[]).map(x=>x.toUpperCase().charCodeAt(0)-65);let type:Question['type']=section;if(type==='single'&&letters.length>1)type='multiple';if(type==='judge')out.push({type,stem,options:['正确','错误'],answer:/^(正确|对|是|TRUE)/i.test(ans),score:2});else if(type==='fill')out.push({type,stem,answer:[ans],score:5});else if(type==='short'||type==='case')out.push({type,stem,answer:type==='short'?[ans]:undefined,score:type==='case'?20:10});else if(options.length>=2)out.push({type,stem,options,answer:type==='multiple'?letters:(letters[0]??0),score:type==='multiple'?4:3});group=[]};for(const line of lines){const h=line.match(heading);if(h){flush('');section=h[1]==='单选题'?'single':h[1]==='多选题'?'multiple':h[1]==='判断题'?'judge':h[1]==='填空题'?'fill':h[1]==='简答题'?'short':'case';insideSection=true;continue}if(!insideSection)continue;if(/^(说明|题量|分值|形式|考试时间|考试要求)/.test(line)||/^(?:\d+[.、．)]\s*)?(题量|分值|形式)：?/.test(line))continue;if(/^(答案|正确答案|参考答案)\s*[:：]?/i.test(line)){flush(line.replace(/^(答案|正确答案|参考答案)\s*[:：]?/i,'').trim());continue}group.push(line)}flush('');return out}

function parseQuestions(text: string): Question[] {
  const lines=text.replace(/\r/g,'').split('\n').map(x=>x.trim()).filter(Boolean);const result:Question[]=[];let section:Question['type']='single',group:string[]=[],insideSection=false;
  const finish=(answerLine:string)=>{if(!group.length)return;const rawAnswer=(answerLine.match(/(?:正确答案|参考答案|答案)\s*[:：]?\s*(.*)/i)?.[1]||'').trim();let first=group.shift()||'';first=first.replace(/^\d+[.、．]\s*/,'').trim();const inline=[first,...group].join('\n');const marker=/(?<![A-Za-z0-9-])([A-F])(?:\s*[.、．]\s*|\s+|(?=[\u4e00-\u9fff]))/g;const matches=[...inline.matchAll(marker)];let stem=first,options:string[]=[];
    if(matches.length>=2){stem=inline.slice(0,matches[0].index).trim().replace(/^\d+[.、．]\s*/,'');options=matches.map((m,i)=>inline.slice((m.index||0)+m[0].length,i+1<matches.length?matches[i+1].index:inline.length).trim()).filter(Boolean)}else{options=group.map(x=>x.replace(/^[A-F]\s*[.、．]\s*/i,'').trim()).filter(Boolean)}
    let type:Question['type']=section;if(/案例分析|案例题/.test(stem))type='case';else if(/简答题|简答/.test(stem))type='short';else if(/判断题/.test(stem)||section==='judge')type='judge';else if(/填空题|_{3,}|（\s*）/.test(stem)&&!options.length)type='fill';const answerPrefix=rawAnswer.match(/^[A-F](?:\s*[,，、]?\s*[A-F])*/i)?.[0]||'';const letters=(answerPrefix.match(/[A-F]/gi)||[]).map(x=>x.toUpperCase().charCodeAt(0)-65);if(section==='multiple'||letters.length>1)type='multiple';
    if(type==='case')result.push({type,stem,score:20});else if(type==='short')result.push({type,stem,answer:rawAnswer? [rawAnswer] : [],score:10});else if(type==='judge'){const yes=/^(正确|对|是|T|TRUE)/i.test(rawAnswer);result.push({type,stem,options:['正确','错误'],answer:yes,score:2});}else if(type==='fill')result.push({type,stem,answer:rawAnswer.split(/[|｜]/).filter(Boolean),score:5});else if(options.length>=2)result.push({type,stem,options,answer:type==='multiple'?letters:(letters[0]??0),score:type==='multiple'?4:3});group=[]};
  for(const line of lines){if(/^单选题\s*$/.test(line)){section='single';group=[];insideSection=true;continue}if(/^多选题\s*$/.test(line)){section='multiple';group=[];insideSection=true;continue}if(/^判断题\s*$/.test(line)){section='judge';group=[];insideSection=true;continue}if(/^填空题\s*$/.test(line)){section='fill';group=[];insideSection=true;continue}if(/^(简答题|简答)\s*$/.test(line)){section='short';group=[];insideSection=true;continue}if(/^(案例分析|案例题)\s*$/.test(line)){section='case';group=[];insideSection=true;continue}if(!insideSection)continue;if(/^(?:正确答案|参考答案|答案)\s*[:：]?/i.test(line)){finish(line);continue}group.push(line)}return result;
}

const typeName:Record<Question['type'],string>={single:'单选题',multiple:'多选题',judge:'判断题',fill:'填空题',short:'简答题',case:'案例分析'};

export default function Home() {
  const [user,setUser]=useState<{id:number;email:string;role:string}|null>(null);
  const [examCount,setExamCount]=useState(0);
  const [showStats,setShowStats]=useState(false);
  const [recordsOpen,setRecordsOpen]=useState(false);
  const [listMode,setListMode]=useState<'view'|'stats'>('stats');
  const [examList,setExamList]=useState<{code:string;title:string;adminKey:string;createdAt:number}[]>([]);
  const [selectedExamCode,setSelectedExamCode]=useState('');
  const [authReady,setAuthReady]=useState(false);
  useEffect(()=>{fetch('/api/auth').then(r=>r.json()).then(d=>{setUser(d.user);setAuthReady(true)})},[]);
  useEffect(()=>{if(user)fetch('/api/exams').then(r=>r.json()).then(d=>{setExamCount(Number(d.count)||0);setExamList(Array.isArray(d.exams)?d.exams:[])})},[user]);
  const inputRef = useRef<HTMLInputElement>(null);
  const [questions, setQuestions] = useState<Question[]>(sample);
  const [fileName, setFileName] = useState('云计算基础考试题.docx');
  const [title, setTitle] = useState('云计算基础知识测验');
  const [duration, setDuration] = useState(30);
  const [startsAt, setStartsAt] = useState('');
  const [endsAt, setEndsAt] = useState('');
  const [expectedCandidates, setExpectedCandidates] = useState(1);
  const [step, setStep] = useState(2);
  const [published, setPublished] = useState(false);
  const [busy, setBusy] = useState(false);
  const [sourceFile, setSourceFile] = useState<File|null>(null);
  const [publishInfo, setPublishInfo] = useState<{code:string;adminKey:string}|null>(null);
  const [message, setMessage] = useState('');
  const [editing, setEditing] = useState<number|null>(null);
  const [singleCount,setSingleCount]=useState(questions.filter(q=>q.type==='single').length);
  const [multipleCount,setMultipleCount]=useState(questions.filter(q=>q.type==='multiple').length);
  const selectedQuestions=useMemo(()=>{const shuffle=<T,>(items:T[])=>items.map(x=>({x,r:Math.random()})).sort((a,b)=>a.r-b.r).map(v=>v.x);const chosen=new Set<Question>([...shuffle(questions.filter(q=>q.type==='single')).slice(0,singleCount),...shuffle(questions.filter(q=>q.type==='multiple')).slice(0,multipleCount)]);return questions.filter(q=>!['single','multiple'].includes(q.type)||chosen.has(q))},[questions,singleCount,multipleCount]);
  const total = useMemo(() => selectedQuestions.reduce((sum, q) => sum + q.score, 0), [selectedQuestions]);

  function downloadTemplate(kind:'word'|'excel') {
    const headers=['题型','题目','选项A','选项B','选项C','选项D','答案','分值'];
    const sampleRows=[['单选题','HTTP 401 表示什么？','未授权','成功','未找到','服务器错误','A','5'],['多选题','以下哪些是数据库？','MySQL','PostgreSQL','Redis','Word','A|B|C','10'],['判断题','HTTPS 比 HTTP 更安全','','','','','正确','2'],['填空题','创建分支的命令是____','','','','','git branch','5'],['简答题','请简述信息安全的三个基本特征。','','','','','','10'],['案例分析','请分析系统响应缓慢的原因并提出方案。','','','','','','20']];
    const esc=(s:string)=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
    const html=`<html><meta charset="utf-8"><table border="1"><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr>${sampleRows.map(row=>`<tr>${row.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</table></html>`;
    const blob=new Blob([html],{type:'application/vnd.ms-excel'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=kind==='word'?'考试题目模板.doc':'考试题目模板.xls';a.click();URL.revokeObjectURL(url);
  }
  async function importExcel(file?:File){if(!file)return;setBusy(true);try{const text=await file.text();const rows=[...text.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)].map(m=>[...m[1].matchAll(/<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/gi)].map(x=>x[1].replace(/<[^>]+>/g,'').replace(/&amp;/g,'&').replace(/&lt;/g,'<').trim()));const data=rows.length?rows.slice(1):text.split(/\r?\n/).filter(Boolean).map(x=>x.split(','));const parsed:Question[]=data.map(r=>{const t=String(r[0]||'单选题'),type=t.includes('多')?'multiple':t.includes('判')?'judge':t.includes('填')?'fill':t.includes('简')?'short':t.includes('案')?'case':'single';const opts=r.slice(2,6).filter(Boolean);const raw=String(r[6]||'');const answer=type==='multiple'?raw.split(/[|,，]/).map(x=>x.trim()).filter(Boolean).map(x=>/^[A-F]$/i.test(x)?x.toUpperCase().charCodeAt(0)-65:Number(x)).filter(x=>typeof x==='number'&&!Number.isNaN(x)):(type==='single'&&/^[A-F]$/i.test(raw)?raw.toUpperCase().charCodeAt(0)-65:type==='judge'?/^(正确|对|true|是)$/i.test(raw):type==='fill'?[raw]:undefined);return{type,stem:String(r[1]||''),options:opts.length?opts:type==='judge'?['正确','错误']:undefined,answer,score:Number(r[7])||5}}).filter(q=>q.stem);if(parsed.length){setQuestions(parsed);setSingleCount(parsed.filter(q=>q.type==='single').length);setMultipleCount(parsed.filter(q=>q.type==='multiple').length);setFileName(file.name);setTitle(file.name.replace(/\.(xlsx?|csv)$/i,''));setStep(2)}}finally{setBusy(false)}}

  async function importWord(file?: File) {
    if (!file) return;
    setBusy(true);
    try {
      const mammoth = await import('mammoth/mammoth.browser');
      const result = await mammoth.extractRawText({ arrayBuffer: await file.arrayBuffer() });
      // Some Word files place A-D options in the same paragraph as the stem.
      // Split those markers before parsing so they are recognized as options.
      const normalizedText = result.value.replace(/(?<!^)(?=[A-FＡ-Ｆ][.、．)、：:]\s*)/gm, '\n');
      const parsed = parseQuestionsCompat(normalizedText);
      if (parsed.length) {setQuestions(parsed);const singleTotal=parsed.filter(q=>q.type==='single').length,multiTotal=parsed.filter(q=>q.type==='multiple').length;const singleMatch=result.value.match(/单选题\s*\d+\s*题随机生成(?:单选题)?\s*(\d+)\s*题/);const multiMatch=result.value.match(/多选题\s*\d+\s*题随机生成(?:多选题)?\s*(\d+)\s*题/);setSingleCount(Math.min(singleTotal,Number(singleMatch?.[1])||singleTotal));setMultipleCount(Math.min(multiTotal,Number(multiMatch?.[1])||multiTotal));}
      setFileName(file.name);
      setSourceFile(file);
      setTitle(file.name.replace(/\.docx?$/i, ''));
      setStep(2);
    } finally { setBusy(false); }
  }

  async function publish() {
    setBusy(true); setMessage('');
    try {
      if (startsAt && endsAt && new Date(endsAt).getTime() <= new Date(startsAt).getTime()) throw new Error('考试结束时间必须晚于开始时间');
      const form = new FormData(); form.set('title', title); form.set('questions', JSON.stringify(selectedQuestions)); form.set('duration', String(duration)); form.set('expectedCandidates', String(expectedCandidates)); form.set('startsAt', startsAt ? String(new Date(startsAt).getTime()) : ''); form.set('endsAt', endsAt ? String(new Date(endsAt).getTime()) : ''); if(sourceFile)form.set('file',sourceFile);
      const response = await fetch('/api/exams',{method:'POST',body:form}); const data=await response.json();
      if(!response.ok)throw new Error(data.error||'发布失败');
      setPublishInfo(data); setPublished(true); setStep(3);
    } catch(error) { setMessage(error instanceof Error?error.message:'发布失败，请重试'); }
    finally { setBusy(false); }
  }

  if(!authReady)return <main className="grid min-h-screen place-items-center bg-[#f4f7fb]">正在载入…</main>;
  if(!user)return <AuthPanel onLogin={setUser}/>;

  return (
    <main className="min-h-screen bg-[#f4f7fb] text-slate-950">
      <header className="border-b border-slate-200/80 bg-white">
        <div className="mx-auto flex h-16 max-w-[1440px] items-center justify-between px-5 lg:px-8">
          <div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#2457e6] text-white"><BookOpenCheck size={20}/></span><span className="text-lg font-bold tracking-tight">Airquality</span><span className="hidden text-sm text-slate-400 sm:inline">在线考试生成器</span></div>
          <div className="flex items-center gap-3 text-sm"><button className="text-slate-500 hover:text-slate-900">使用帮助</button><span className="grid size-9 place-items-center rounded-full bg-slate-900 font-semibold text-white">林</span></div>
        </div>
      </header>

      {user.role==='admin'&&<InviteBanner/>}

      {!published&&<div className="border-b border-amber-200 bg-amber-50"><div className="mx-auto flex max-w-[1440px] flex-wrap items-center gap-4 px-5 py-3 text-sm lg:px-8"><label className="flex items-center gap-3 font-semibold">应考人数<Input type="number" min={1} max={10000} value={expectedCandidates} onChange={e=>setExpectedCandidates(Math.max(1,Math.min(10000,Number(e.target.value)||1)))} className="h-9 w-24 bg-white" /></label><span className="text-amber-800">考试时长结束后统一开放答案；考生交卷后立即看到个人得分。</span></div></div>}

      {!published&&<div className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-[1440px] flex-wrap items-end gap-4 px-5 py-4 text-sm lg:px-8"><label className="font-semibold">考试开始时间<Input type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)} className="mt-1 h-9 w-56 bg-white" /></label><label className="font-semibold">考试结束时间<Input type="datetime-local" value={endsAt} onChange={e=>setEndsAt(e.target.value)} className="mt-1 h-9 w-56 bg-white" /></label><span className="pb-2 text-slate-500">不填写则发布后立即开放</span></div></div>}
      {!published&&<div className="mx-auto flex max-w-[1440px] flex-wrap gap-2 px-5 pb-3 lg:px-8"><Button variant="outline" size="sm" onClick={()=>document.getElementById('excel-input')?.click()}>导入 Excel</Button><Button variant="ghost" size="sm" onClick={()=>downloadTemplate('word')}><Download size={15}/>Word 模板</Button><Button variant="ghost" size="sm" onClick={()=>downloadTemplate('excel')}><Download size={15}/>Excel 模板</Button><input id="excel-input" type="file" accept=".xls,.xlsx,.csv" className="hidden" onChange={e=>importExcel(e.target.files?.[0])}/></div>}
      <div className="mx-auto grid max-w-[1440px] gap-0 lg:grid-cols-[250px_1fr]">
        <aside className="hidden min-h-[calc(100vh-64px)] border-r border-slate-200 bg-white p-5 lg:block">
          <Button className="mb-7 h-11 w-full bg-[#2457e6] hover:bg-[#1c49c5]" onClick={() => { setPublished(false); setPublishInfo(null); setMessage('请选择整理好的 Word 试卷'); setStep(1); window.setTimeout(()=>inputRef.current?.click(),0); }}><Plus/>新建考试</Button>
          {!published&&<div className="mb-6 space-y-3 rounded-xl border border-slate-200 bg-slate-50 p-3"><label className="block text-sm font-semibold">应考人数<Input type="number" min={1} max={10000} value={expectedCandidates} onChange={e=>setExpectedCandidates(Math.max(1,Math.min(10000,Number(e.target.value)||1)))} className="mt-1 h-9 bg-white" /></label><label className="block text-sm font-semibold">考试开始时间<Input type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)} className="mt-1 h-9 w-full bg-white" /></label><label className="block text-sm font-semibold">考试结束时间<Input type="datetime-local" value={endsAt} onChange={e=>setEndsAt(e.target.value)} className="mt-1 h-9 w-full bg-white" /></label><div className="flex flex-wrap gap-1"><Button variant="outline" size="sm" onClick={()=>document.getElementById('excel-input')?.click()}>导入 Excel</Button><Button variant="ghost" size="sm" onClick={()=>downloadTemplate('word')}>Word 模板</Button><Button variant="ghost" size="sm" onClick={()=>downloadTemplate('excel')}>Excel 模板</Button></div></div>}
          <nav className="space-y-1 text-sm"><button className="nav-active w-full" onClick={()=>{setListMode('view');setRecordsOpen(v=>!v);setPublished(false);setShowStats(false);setStep(2);setMessage(`当前账号共 ${examCount} 场考试`)}}><FileText size={18}/>我的考试<span className="ml-auto rounded-full bg-blue-100 px-2 text-xs text-blue-700">{examCount}</span></button><button className="nav-item w-full" onClick={()=>{setListMode('stats');setRecordsOpen(v=>!v)}}><Users size={18}/>考试记录<span className="ml-auto text-xs text-slate-400">{recordsOpen?'收起':'展开'}</span></button></nav>
          <div className={`${recordsOpen?'mt-3':'hidden'} border-t pt-3`}><p className="mb-2 px-3 text-xs font-semibold text-slate-400">{listMode==='stats'?'选择考试查看记录':'选择考试查看题目'}</p>{examList.length?examList.map((x)=><div className="flex items-center" key={x.code}><button className={`recent min-w-0 flex-1 ${selectedExamCode===x.code?'text-blue-700':''}`} onClick={async()=>{setSelectedExamCode(x.code);setTitle(x.title);setPublishInfo({code:x.code,adminKey:x.adminKey});if(listMode==='stats'){setPublished(true);setShowStats(true)}else{const r=await fetch(`/api/exams/${x.code}?key=${x.adminKey}`);const d=await r.json();if(r.ok){setQuestions(d.questions||[]);setSingleCount((d.questions||[]).filter((q:any)=>q.type==='single').length);setMultipleCount((d.questions||[]).filter((q:any)=>q.type==='multiple').length);setPublished(false);setShowStats(false);setStep(2)}}setMessage('')}}><span className={`size-2 rounded-full ${selectedExamCode===x.code?'bg-blue-500':'bg-slate-300'}`}/><span className="truncate">{x.title}</span></button><button className="px-2 text-xs text-rose-500" onClick={async()=>{if(!window.confirm(`确定删除“${x.title}”及其成绩吗？`))return;const r=await fetch(`/api/exams/${x.code}?key=${x.adminKey}`,{method:'DELETE'});if(r.ok){setExamList(all=>all.filter(e=>e.code!==x.code));setExamCount(n=>Math.max(0,n-1));setMessage('考试已删除')}}}>删除</button></div>):<p className="px-3 text-sm text-slate-400">暂无考试</p>}</div>
        </aside>

        <section className="min-w-0 p-5 sm:p-8 lg:p-10">
          <div className="mx-auto max-w-5xl">
            <div className="mb-8 flex justify-end"><div className="flex items-center gap-2 text-xs font-semibold text-slate-400">{['导入题目','检查试卷','发布考试'].map((x,i)=><div className="flex items-center gap-2" key={x}><span className={`grid size-7 place-items-center rounded-full ${step>i?'bg-[#2457e6] text-white':'bg-slate-200'}`}>{step>i?<Check size={14}/>:i+1}</span><span className={step===i+1?'text-slate-800':''}>{x}</span>{i<2&&<ChevronRight size={14}/>}</div>)}</div></div>

            {published && publishInfo ? <Published title={title} count={selectedQuestions.length} total={total} code={publishInfo.code} adminKey={publishInfo.adminKey} showStats={showStats} setShowStats={setShowStats}/> : <div className="grid gap-6 xl:grid-cols-[1fr_300px]">
              <div className="space-y-5">
                <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7">
                  <div className="mb-5 flex items-start justify-between"><div><h2 className="font-bold">试卷信息</h2><p className="mt-1 text-sm text-slate-500">已从文档识别考试标题和题目</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">识别完成</span></div>
                  <div className="grid gap-4 sm:grid-cols-[1fr_150px]"><label className="block text-sm font-semibold">考试名称<Input value={title} onChange={(e)=>setTitle(e.target.value)} className="mt-2 h-11" /></label><label className="block text-sm font-semibold">考试时长（分钟）<Input type="number" min={1} max={240} value={duration} onChange={e=>setDuration(Math.max(1,Math.min(240,Number(e.target.value)||1)))} className="mt-2 h-11" /></label></div><div className="mt-4 grid gap-4 rounded-xl bg-slate-50 p-4 sm:grid-cols-2"><label className="text-sm font-semibold">单选题随机抽取 <span className="font-normal text-slate-500">（题库 {questions.filter(q=>q.type==='single').length} 题）</span><Input className="mt-2 bg-white" type="number" min={0} max={questions.filter(q=>q.type==='single').length} value={singleCount} onChange={e=>setSingleCount(Math.max(0,Math.min(questions.filter(q=>q.type==='single').length,Number(e.target.value))))}/></label><label className="text-sm font-semibold">多选题随机抽取 <span className="font-normal text-slate-500">（题库 {questions.filter(q=>q.type==='multiple').length} 题）</span><Input className="mt-2 bg-white" type="number" min={0} max={questions.filter(q=>q.type==='multiple').length} value={multipleCount} onChange={e=>setMultipleCount(Math.max(0,Math.min(questions.filter(q=>q.type==='multiple').length,Number(e.target.value))))}/></label></div>
                  <div className="mt-5 flex items-center gap-3 rounded-xl border border-blue-100 bg-blue-50/70 p-4"><span className="grid size-10 place-items-center rounded-lg bg-white text-blue-600 shadow-sm"><FileText size={20}/></span><div className="min-w-0"><p className="truncate text-sm font-semibold">{fileName}</p><p className="text-xs text-slate-500">题库识别 {questions.length} 道 · 发布抽取 {selectedQuestions.length} 道 · 满分 {total} 分</p></div><Button variant="outline" size="sm" className="ml-auto" onClick={()=>inputRef.current?.click()}>{busy?'解析中…':'重新导入'}</Button><input ref={inputRef} type="file" accept=".doc,.docx" className="hidden" onChange={(e)=>importWord(e.target.files?.[0])}/></div>
                </section>
                <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b p-5 sm:px-7"><div><h2 className="font-bold">检查题目</h2><p className="mt-1 text-sm text-slate-500">识别有误时，可逐题修改题型、内容、答案和分值</p></div><Button variant="outline" size="sm" onClick={()=>{setQuestions(q=>[...q,{type:'single',stem:'新题目',options:['选项 A','选项 B'],answer:0,score:5}]);setEditing(questions.length)}}><Plus/>添加题目</Button></div><div className="divide-y">{questions.map((q,i)=><article key={i} className="relative p-5 sm:px-7"><Button aria-label="编辑题目" variant="ghost" size="sm" className="absolute right-4 top-4" onClick={()=>setEditing(editing===i?null:i)}>{editing===i?<X/>:<Pencil/>}{editing===i?'收起':'修改'}</Button><div className="mb-4 flex gap-3 pr-20"><span className="grid size-7 shrink-0 place-items-center rounded-lg bg-slate-100 text-sm font-bold">{i+1}</span><div><h3 className="font-semibold leading-7">{q.stem}</h3><p className="text-xs text-slate-400">{typeName[q.type]} · {q.score} 分 {q.type==='case'?'· 人工评分':''}</p></div></div>{q.options?<div className="grid gap-2 pl-10 sm:grid-cols-2">{q.options.map((o,j)=>{const correct=Array.isArray(q.answer)?q.answer.includes(j):j===q.answer;return <div key={j} className={`flex items-center gap-3 rounded-lg border px-3 py-2.5 text-sm ${correct?'border-blue-300 bg-blue-50 text-blue-800':'border-slate-200'}`}><span className={`grid size-6 place-items-center rounded-full text-xs font-bold ${correct?'bg-blue-600 text-white':'bg-slate-100'}`}>{String.fromCharCode(65+j)}</span>{o}{correct&&<Check className="ml-auto" size={15}/>}</div>})}</div>:<div className="ml-10 rounded-lg bg-slate-50 p-3 text-sm text-slate-500">{q.type==='fill'?`参考答案：${(q.answer as string[]).join(' / ')}`:'考生提交分析后，由教师在成绩页评分'}</div>}{editing===i&&<QuestionEditor question={q} onChange={next=>setQuestions(all=>all.map((item,index)=>index===i?next:item))}/>}</article>)}</div></section>
              </div>
              <aside className="space-y-5"><div className="rounded-2xl bg-[#11204a] p-6 text-white shadow-xl shadow-blue-950/10"><div className="mb-5 flex items-center gap-2 text-sm font-semibold text-blue-200"><Sparkles size={17}/>准备发布</div><div className="mb-5 grid grid-cols-2 gap-3"><Stat n={selectedQuestions.length} label="抽取题目"/><Stat n={total} label="总分"/></div><div className="space-y-3 border-t border-white/10 py-5 text-sm"><p className="flex justify-between text-blue-100"><span className="flex items-center gap-2"><Clock3 size={15}/>考试时长</span><strong className="text-white">{duration} 分钟</strong></p><p className="flex justify-between text-blue-100"><span>交卷后</span><strong className="text-white">自动判分</strong></p></div><Button className="h-12 w-full bg-white font-bold text-[#17316f] hover:bg-blue-50" onClick={publish} disabled={busy}>{busy?'正在生成…':'生成考试链接'}<ChevronRight/></Button>{message&&<p className="mt-3 text-sm text-rose-300">{message}</p>}</div><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="mb-3 flex items-center gap-2 font-semibold"><UploadCloud size={18} className="text-blue-600"/>Word 格式提示</div><p className="text-sm leading-6 text-slate-500">支持无序号选项、同一行多个选项及“答案/正确答案”等写法，导入后可逐题调整。</p></div></aside>
            </div>}
          </div>
        </section>
      </div>
    </main>
  );
}

function AuthPanel({onLogin}:{onLogin:(user:any)=>void}){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[register,setRegister]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function submit(){setBusy(true);setError('');const r=await fetch('/api/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:register?'register':'login',email,password})});const d=await r.json();if(r.ok)onLogin(d.user);else setError(d.error||'操作失败');setBusy(false)}return <main className="grid min-h-screen place-items-center bg-[#f4f7fb] p-5"><div className="w-full max-w-md rounded-3xl border bg-white p-8 shadow-xl"><div className="text-center"><span className="mx-auto grid size-12 place-items-center rounded-xl bg-[#2457e6] text-white"><BookOpenCheck/></span><h1 className="mt-4 text-2xl font-bold">Airquality</h1><p className="mt-2 text-sm text-slate-500">{register?'创建管理员账号':'登录考试管理后台'}</p></div><label className="mt-7 block text-sm font-semibold">邮箱<Input className="mt-2 h-11" type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="mt-4 block text-sm font-semibold">密码<Input className="mt-2 h-11" type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="mt-3 text-sm text-rose-600">{error}</p>}<Button className="mt-5 h-11 w-full bg-[#2457e6]" disabled={busy} onClick={submit}>{busy?'处理中…':register?'注册并进入':'登录'}</Button><button className="mt-4 w-full text-sm text-blue-600" onClick={()=>{setRegister(!register);setError('')}}>{register?'已有账号，返回登录':'首次使用？注册第一个管理员账号'}</button></div></main>}
function InviteBanner(){const[url,setUrl]=useState('');async function create(){const r=await fetch('/api/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'invite'})});const d=await r.json();if(r.ok)setUrl(`${window.location.origin}/?invite=${d.token}`)}return <div className="border-b border-blue-100 bg-blue-50"><div className="mx-auto flex max-w-[1440px] flex-wrap items-center gap-3 px-5 py-3 text-sm lg:px-8"><span className="font-semibold text-blue-900">管理员</span><Button size="sm" onClick={create}>生成同事邀请链接</Button>{url&&<Input readOnly value={url} className="h-9 max-w-xl bg-white"/>}</div></div>}

function Stat({n,label}:{n:number;label:string}) { return <div className="rounded-xl bg-white/8 p-4"><strong className="text-2xl">{n}</strong><p className="mt-1 text-xs text-blue-200">{label}</p></div> }
function QuestionEditor({question,onChange}:{question:Question;onChange:(q:Question)=>void}){const answerText=question.type==='single'?String.fromCharCode(65+Number(question.answer||0)):question.type==='multiple'?(question.answer as number[]||[]).map(i=>String.fromCharCode(65+i)).join(','):question.type==='fill'?(question.answer as string[]||[]).join('｜'):'';function changeType(type:Question['type']){if(type==='single')onChange({...question,type,options:question.options||['选项 A','选项 B'],answer:0});else if(type==='multiple')onChange({...question,type,options:question.options||['选项 A','选项 B'],answer:[]});else if(type==='fill')onChange({...question,type,options:undefined,answer:['']});else onChange({...question,type,options:undefined,answer:undefined,score:Math.max(10,question.score)})}function setAnswer(value:string){if(question.type==='single')onChange({...question,answer:Math.max(0,value.toUpperCase().charCodeAt(0)-65)});else if(question.type==='multiple')onChange({...question,answer:(value.match(/[A-Z]/gi)||[]).map(x=>x.toUpperCase().charCodeAt(0)-65)});else if(question.type==='fill')onChange({...question,answer:value.split(/[|｜]/).map(x=>x.trim()).filter(Boolean)})}return <div className="mt-5 space-y-4 rounded-xl border border-blue-200 bg-blue-50/40 p-4"><div className="grid gap-4 sm:grid-cols-[1fr_120px]"><label className="text-sm font-semibold">题型<select className="mt-2 h-10 w-full rounded-md border bg-white px-3 font-normal" value={question.type} onChange={e=>changeType(e.target.value as Question['type'])}><option value="single">单选题</option><option value="multiple">多选题</option><option value="fill">填空题</option><option value="case">案例分析</option></select></label><label className="text-sm font-semibold">分值<Input className="mt-2 bg-white" type="number" min={1} value={question.score} onChange={e=>onChange({...question,score:Math.max(1,Number(e.target.value))})}/></label></div><label className="block text-sm font-semibold">题目<Input className="mt-2 bg-white" value={question.stem} onChange={e=>onChange({...question,stem:e.target.value})}/></label>{question.options&&<div className="grid gap-3 sm:grid-cols-2">{question.options.map((option,index)=><label key={index} className="text-sm font-semibold">选项 {String.fromCharCode(65+index)}<Input className="mt-2 bg-white" value={option} onChange={e=>onChange({...question,options:question.options?.map((o,i)=>i===index?e.target.value:o)})}/></label>)}</div>}{question.type!=='case'&&<label className="block text-sm font-semibold">{question.type==='fill'?'参考答案（多个答案用｜分隔）':question.type==='multiple'?'正确选项（例如 A,B）':'正确选项（例如 A）'}<Input className="mt-2 bg-white" value={answerText} onChange={e=>setAnswer(e.target.value)}/></label>}</div>}
function Published({title,count,total,code,adminKey,showStats,setShowStats}:{title:string;count:number;total:number;code:string;adminKey:string;showStats:boolean;setShowStats:(v:boolean)=>void}) {
  const [link,setLink] = useState(`/e/${code}`);
  const [qr, setQr] = useState('');
  useEffect(() => { const absolute=`${window.location.origin}/e/${code}`;setLink(absolute);import('qrcode').then((QRCode) => QRCode.toDataURL(absolute, { width: 220, margin: 1, color: { dark: '#11204a', light: '#ffffff' } })).then(setQr); }, [code]);
  if(showStats)return <Stats code={code} adminKey={adminKey} onBack={()=>setShowStats(false)}/>;
  return <div className="mx-auto max-w-2xl rounded-3xl border border-slate-200 bg-white p-7 text-center shadow-sm sm:p-10"><span className="mx-auto grid size-16 place-items-center rounded-full bg-emerald-50 text-emerald-600"><Check size={30}/></span><h2 className="mt-5 text-2xl font-bold">考试已生成</h2><p className="mt-2 text-slate-500">“{title}”可以发给学员了</p><div className="my-8 grid gap-5 rounded-2xl bg-slate-50 p-5 text-left sm:grid-cols-[1fr_140px]"><div><p className="text-xs font-semibold text-slate-400">考试链接</p><div className="mt-2 flex"><Input readOnly value={link} className="rounded-r-none bg-white"/><Button className="rounded-l-none bg-[#2457e6]" onClick={()=>navigator.clipboard?.writeText(link)}><Link2/>复制</Button></div><div className="mt-5 flex gap-6 text-sm text-slate-500"><span><b className="text-slate-900">{count}</b> 道题</span><span><b className="text-slate-900">{total}</b> 分</span><span>自动判分</span></div></div><div className="grid place-items-center rounded-xl border border-slate-200 bg-white p-3">{qr?<img src={qr} alt="考试二维码" className="size-[88px]"/>:<QrCode size={88} strokeWidth={1.4}/>}<span className="text-[11px] text-slate-400">扫码参加考试</span></div></div><div className="flex flex-col justify-center gap-3 sm:flex-row"><Button variant="outline" onClick={()=>window.open(link,'_blank')}>预览考生页面</Button><Button className="bg-[#2457e6] hover:bg-[#1c49c5]" onClick={()=>setShowStats(true)}><Users/>查看考试记录</Button></div></div>
}

type StatsData={title:string;count:number;pendingCount:number;average:number;passRate:number;questions:Array<{index:number;type:string;stem:string;score:number}>;attempts:Array<{id:number;candidate_name:string;organization:string;answers:Array<number|number[]|string>;score:number;total_score:number;grading_status:string;submitted_at:number}>};
function Stats({code,adminKey,onBack}:{code:string;adminKey:string;onBack:()=>void}){const[data,setData]=useState<StatsData|null>(null);const[grading,setGrading]=useState<number|null>(null);const[scores,setScores]=useState<Record<string,number>>({});const load=()=>fetch(`/api/exams/${code}/stats?key=${adminKey}`).then(r=>r.json()).then(setData);useEffect(()=>{load()},[code,adminKey]);async function save(attemptId:number){await fetch(`/api/exams/${code}/stats`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({key:adminKey,attemptId,scores})});setGrading(null);setScores({});load()}async function exportScores(){const r=await fetch(`/api/exams/${code}/export?key=${adminKey}`);const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${data?.title||'考试'}-成绩.csv`;a.click();URL.revokeObjectURL(url)}if(!data)return <p className="p-10 text-center text-slate-500">正在读取成绩…</p>;return <div><div className="flex justify-between"><Button variant="outline" onClick={onBack}>返回分享</Button><Button onClick={exportScores} className="bg-[#2457e6]"><Download/>导出全部成绩</Button></div><div className="mt-5 grid gap-4 sm:grid-cols-4"><Metric label="已交卷" value={data.count}/><Metric label="待评分" value={data.pendingCount}/><Metric label="平均分" value={data.average}/><Metric label="及格率" value={`${data.passRate}%`}/></div><div className="mt-6 overflow-hidden rounded-2xl border bg-white"><div className="border-b p-5"><h2 className="font-bold">考试记录</h2></div>{data.attempts.length?data.attempts.map(a=><div key={a.id} className="border-b p-5 last:border-0"><div className="flex flex-wrap items-center gap-4 text-sm"><div className="mr-auto"><b>{a.candidate_name}</b><p className="mt-1 text-xs text-slate-500">{a.organization||'未填写单位'}</p></div><span>{a.score} / {a.total_score} 分</span><span className={a.grading_status==='pending'?'font-semibold text-amber-600':'text-emerald-600'}>{a.grading_status==='pending'?'待评分':'已评分'}</span><span className="text-slate-400">{new Date(a.submitted_at).toLocaleString('zh-CN')}</span>{a.grading_status==='pending'&&<Button size="sm" onClick={()=>setGrading(grading===a.id?null:a.id)}>批改案例题</Button>}</div>{grading===a.id&&<div className="mt-5 space-y-4 rounded-xl bg-slate-50 p-5">{data.questions.filter(q=>q.type==='case').map(q=><div key={q.index}><b className="text-sm">{q.index+1}. {q.stem}</b><p className="my-2 rounded-lg bg-white p-3 text-sm leading-6">{String(a.answers[q.index]||'未作答')}</p><label className="flex items-center gap-3 text-sm font-semibold">评分 <Input className="w-24" type="number" min={0} max={q.score} value={scores[String(q.index)]??''} onChange={e=>setScores(s=>({...s,[q.index]:Number(e.target.value)}))}/> / {q.score} 分</label></div>)}<Button className="bg-[#2457e6]" onClick={()=>save(a.id)}>保存评分</Button></div>}</div>):<p className="p-10 text-center text-slate-400">还没有考生交卷</p>}</div></div>}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">{label}</p><strong className="mt-2 block text-3xl">{value}</strong></div>}
